/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 *
 * You can specify multiple sidebar sections.
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // This can be kept for simple documentation or removed if a fully custom sidebar is preferred.
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generates a sidebar from the docs folder itself
    },
  ],

  // Custom sidebar for "My Book" with modules
  myBookSidebar: [
    'intro', // The 'intro.md' page

    {
      type: 'category',
      label: 'Module: Theming & Custom UI',
      collapsed: false,
      items: [
        '001-theming-custom-ui-spec',
        '002-theming-custom-ui-plan',
        '002-theming-custom-ui-spec',
        '006-theming-custom-ui-data-model',
        '006-theming-custom-ui-plan',
        '006-theming-custom-ui-quickstart',
        '006-theming-custom-ui-research',
        '006-theming-custom-ui-spec',
        '006-theming-custom-ui-tasks',
      ],
    },
    {
      type: 'category',
      label: 'Module: Intro Physical AI',
      collapsed: false,
      items: [
        '005-intro-physical-ai-spec',
      ],
    },
    {
      type: 'category',
      label: 'Module: ROS 2 Fundamentals',
      collapsed: false,
      items: [
        '006-module-1-ros2-fundamentals-spec',
      ],
    },
    {
      type: 'category',
      label: 'Module: Digital Twin',
      collapsed: false,
      items: [
        '007-module-2-digital-twin-spec',
      ],
    },
    {
      type: 'category',
      label: 'Module: Isaac AI Core',
      collapsed: false,
      items: [
        '008-module-3-isaac-ai-core-spec',
        '009-module-3-isaac-ai-core-spec',
        '010-module-3-isaac-ai-core-spec',
      ],
    },
    {
      type: 'category',
      label: 'Module: VLA Humanoids',
      collapsed: false,
      items: [
        '011-module-4-vla-humanoids-spec',
        '012-module-4-vla-humanoids-spec',
      ],
    },
  ],
};

module.exports = sidebars;
